local parser = require("todoist-tui.parser")

describe("parser", function()
  it("parses project and tag refs", function()
    local res = parser.parse("fix the splash not opening @fix #work")
    assert.are.equal("fix the splash not opening", res.content)
    assert.are.equal("work", res.project)
    assert.are.same({ "fix" }, res.tags)
  end)

  it("supports multiple tags", function()
    local res = parser.parse("write docs @docs @writing #docs")
    assert.are.equal("write docs", res.content)
    assert.are.equal("docs", res.project)
    assert.are.same({ "docs", "writing" }, res.tags)
  end)

  it("strips trailing punctuation from refs", function()
    local res = parser.parse("call mom @home, #errands.")
    assert.are.equal("call mom", res.content)
    assert.are.equal("errands", res.project)
    assert.are.same({ "home" }, res.tags)
    assert.is_nil(res.priority)
  end)

  it("parses priority tags", function()
    local res = parser.parse("fix the splash not opening @fix #work p1")
    assert.are.equal("fix the splash not opening", res.content)
    assert.are.equal("work", res.project)
    assert.are.same({ "fix" }, res.tags)
    assert.are.equal(1, res.priority)
  end)

  it("parses priority tags case-insensitively and strips punctuation", function()
    local res = parser.parse("do this P3!")
    assert.are.equal("do this", res.content)
    assert.are.equal(3, res.priority)
  end)

  it("ignores invalid priorities like p5 or p0", function()
    local res = parser.parse("do this p5 and p0")
    assert.are.equal("do this p5 and p0", res.content)
    assert.is_nil(res.priority)
  end)

  it("no refs returns content unchanged", function()
    local res = parser.parse("just a normal task")
    assert.are.equal("just a normal task", res.content)
    assert.is_nil(res.project)
    assert.are.same({}, res.tags)
  end)

  it("bare @ or # not treated as ref", function()
    local res = parser.parse("email @ someone #")
    assert.are.equal("email @ someone #", res.content)
    assert.is_nil(res.project)
    assert.are.same({}, res.tags)
  end)

  it("mid-word @/# not treated as ref", function()
    local res = parser.parse("fix bug#123 and user@domain.com")
    assert.are.equal("fix bug#123 and user@domain.com", res.content)
    assert.is_nil(res.project)
    assert.are.same({}, res.tags)
  end)
end)
